### ISSUE TITLE
should be opam packaged if there are some users

### ISSUE THREAD

**Issue by UnixJunkie** [mathiasbourgoin/ocp2opam#1]

**Comment by mathiasbourgoin** [comment]
There are probably no users for this tool. It was based on ocp-build which     I believe is not really used anymore.

**Comment by UnixJunkie** [comment]
OK, I saw you used this tool to do the first package for spoc.
I rewrote a new opam file by hand for the new release of spoc.
FYI, apparently jbuilder is the thing that may eradicate ocamlbuild and all competitors soon.
It is quite nice to use.
